# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.4

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/algomorph/Factory/pyboostcvconverter

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/algomorph/Factory/pyboostcvconverter

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"python\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/algomorph/Factory/pyboostcvconverter/CMakeFiles /home/algomorph/Factory/pyboostcvconverter/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/algomorph/Factory/pyboostcvconverter/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pbcvt

# Build rule for target.
pbcvt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pbcvt
.PHONY : pbcvt

# fast build rule for target.
pbcvt/fast:
	$(MAKE) -f CMakeFiles/pbcvt.dir/build.make CMakeFiles/pbcvt.dir/build
.PHONY : pbcvt/fast

src/pyboost_cv2_converter.o: src/pyboost_cv2_converter.cpp.o

.PHONY : src/pyboost_cv2_converter.o

# target to build an object file
src/pyboost_cv2_converter.cpp.o:
	$(MAKE) -f CMakeFiles/pbcvt.dir/build.make CMakeFiles/pbcvt.dir/src/pyboost_cv2_converter.cpp.o
.PHONY : src/pyboost_cv2_converter.cpp.o

src/pyboost_cv2_converter.i: src/pyboost_cv2_converter.cpp.i

.PHONY : src/pyboost_cv2_converter.i

# target to preprocess a source file
src/pyboost_cv2_converter.cpp.i:
	$(MAKE) -f CMakeFiles/pbcvt.dir/build.make CMakeFiles/pbcvt.dir/src/pyboost_cv2_converter.cpp.i
.PHONY : src/pyboost_cv2_converter.cpp.i

src/pyboost_cv2_converter.s: src/pyboost_cv2_converter.cpp.s

.PHONY : src/pyboost_cv2_converter.s

# target to generate assembly for a file
src/pyboost_cv2_converter.cpp.s:
	$(MAKE) -f CMakeFiles/pbcvt.dir/build.make CMakeFiles/pbcvt.dir/src/pyboost_cv2_converter.cpp.s
.PHONY : src/pyboost_cv2_converter.cpp.s

src/pyboost_cv3_converter.o: src/pyboost_cv3_converter.cpp.o

.PHONY : src/pyboost_cv3_converter.o

# target to build an object file
src/pyboost_cv3_converter.cpp.o:
	$(MAKE) -f CMakeFiles/pbcvt.dir/build.make CMakeFiles/pbcvt.dir/src/pyboost_cv3_converter.cpp.o
.PHONY : src/pyboost_cv3_converter.cpp.o

src/pyboost_cv3_converter.i: src/pyboost_cv3_converter.cpp.i

.PHONY : src/pyboost_cv3_converter.i

# target to preprocess a source file
src/pyboost_cv3_converter.cpp.i:
	$(MAKE) -f CMakeFiles/pbcvt.dir/build.make CMakeFiles/pbcvt.dir/src/pyboost_cv3_converter.cpp.i
.PHONY : src/pyboost_cv3_converter.cpp.i

src/pyboost_cv3_converter.s: src/pyboost_cv3_converter.cpp.s

.PHONY : src/pyboost_cv3_converter.s

# target to generate assembly for a file
src/pyboost_cv3_converter.cpp.s:
	$(MAKE) -f CMakeFiles/pbcvt.dir/build.make CMakeFiles/pbcvt.dir/src/pyboost_cv3_converter.cpp.s
.PHONY : src/pyboost_cv3_converter.cpp.s

src/python_module.o: src/python_module.cpp.o

.PHONY : src/python_module.o

# target to build an object file
src/python_module.cpp.o:
	$(MAKE) -f CMakeFiles/pbcvt.dir/build.make CMakeFiles/pbcvt.dir/src/python_module.cpp.o
.PHONY : src/python_module.cpp.o

src/python_module.i: src/python_module.cpp.i

.PHONY : src/python_module.i

# target to preprocess a source file
src/python_module.cpp.i:
	$(MAKE) -f CMakeFiles/pbcvt.dir/build.make CMakeFiles/pbcvt.dir/src/python_module.cpp.i
.PHONY : src/python_module.cpp.i

src/python_module.s: src/python_module.cpp.s

.PHONY : src/python_module.s

# target to generate assembly for a file
src/python_module.cpp.s:
	$(MAKE) -f CMakeFiles/pbcvt.dir/build.make CMakeFiles/pbcvt.dir/src/python_module.cpp.s
.PHONY : src/python_module.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... pbcvt"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... edit_cache"
	@echo "... src/pyboost_cv2_converter.o"
	@echo "... src/pyboost_cv2_converter.i"
	@echo "... src/pyboost_cv2_converter.s"
	@echo "... src/pyboost_cv3_converter.o"
	@echo "... src/pyboost_cv3_converter.i"
	@echo "... src/pyboost_cv3_converter.s"
	@echo "... src/python_module.o"
	@echo "... src/python_module.i"
	@echo "... src/python_module.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

